/**
 * @file Type definitions related to states/provinces
 */

export enum USStates {
    Alabama = 'Alabama',
    Alaska = 'Alaska',
    AmericanSamoa = 'American Samoa',
    Arizona = 'Arizona',
    Arkansas = 'Arkansas',
    California = 'California',
    Colorado = 'Colorado',
    Connecticut = 'Connecticut',
    Delaware = 'Delaware',
    DistrictOfColumbia = 'District Of Columbia',
    FederatedStatesOfMicronesia = 'Federated States Of Micronesia',
    Florida = 'Florida',
    Georgia = 'Georgia',
    Guam = 'Guam',
    Hawaii = 'Hawaii',
    Idaho = 'Idaho',
    Illinois = 'Illinois',
    Indiana = 'Indiana',
    Iowa = 'Iowa',
    Kansas = 'Kansas',
    Kentucky = 'Kentucky',
    Louisiana = 'Louisiana',
    Maine = 'Maine',
    Marshall = 'Marshall Islands',
    Maryland = 'Maryland',
    Massachusetts = 'Massachusetts',
    Michigan = 'Michigan',
    Minnesota = 'Minnesota',
    Mississippi = 'Mississippi',
    Missouri = 'Missouri',
    Montana = 'Montana',
    Nebraska = 'Nebraska',
    Nevada = 'Nevada',
    NewHampshire = 'New Hampshire',
    NewJersey = 'New Jersey',
    NewMexico = 'New Mexico',
    NewYork = 'New York',
    NorthCarolina = 'North Carolina',
    NorthDakota = 'North Dakota',
    NorthernMarianaIslands = 'Northern Mariana Islands',
    Ohio = 'Ohio',
    Oklahoma = 'Oklahoma',
    Oregon = 'Oregon',
    Palau = 'Palau',
    Pennsylvania = 'Pennsylvania',
    PuertoRico = 'Puerto Rico',
    RhodeIsland = 'Rhode Island',
    SouthCarolina = 'South Carolina',
    SouthDakota = 'South Dakota',
    Tennessee = 'Tennessee',
    Texas = 'Texas',
    Utah = 'Utah',
    Vermont = 'Vermont',
    VirginIslands = 'Virgin Islands',
    Virginia = 'Virginia',
    Washington = 'Washington',
    WestVirginia = 'West Virginia',
    Wisconsin = 'Wisconsin',
    Wyoming = 'Wyoming',
}

export enum CanadianProvinces {
    Alberta = 'Alberta',
    BritishColumbia = 'British Columbia',
    Manitoba = 'Manitoba',
    NewBrunswick = 'New Brunswick',
    NewfoundlandAndLabrador = 'Newfoundland and Labrador',
    NorthwestTerritories = 'Northwest Territories',
    NovaScotia = 'Nova Scotia',
    Nunavut = 'Nunavut',
    Ontario = 'Ontario',
    PrinceEdwardIsland = 'Prince Edward Island',
    Quebec = 'Quebec',
    Saskatchewan = 'Saskatchewan',
    Yukon = 'Yukon',
}
