# deploy-staging.yml
name: Deploy Staging on Push to Main
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: 0.1.0
      REGISTRY: ghcr.io
      NODE_ENV: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
          build-args: |
            REACT_APP_CUSTOM_NODE_ENV=${{ env.NODE_ENV }}
