# deploy-staging.yml
name: Deploy Staging on Push to Main
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
      CONTAINER_REGISTRY: ghcr.io
      REACT_APP_CUSTOM_NODE_ENV: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:${{ github.ref }}
            ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}
            ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:latest
          build-args: |
            REACT_APP_CUSTOM_NODE_ENV=${{ env.REACT_APP_CUSTOM_NODE_ENV }}
